development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  host: localhost
